### ISSUE TITLE
DNS changes for Kubernetes cluster

### ISSUE THREAD

**Issue by bartjkdp** [VNG-Realisatie/nlx#10]
Could we change the DNS settings of our domain to:

```
@ A 83.96.238.108
@ AAAA 2a02:348:5e6:1::8c0
* A 83.96.238.108
* AAAA 2a02:348:5e6:1::8c0
```

All traffic to the domain will then be handled by the Kubernetes load balancer.

**Comment by ehotting** [comment]
@bartjkdp Can you review & close if resolved?

**Comment by bartjkdp** [comment]
The naked and www record seem to be fine, but I am missing the wildcard record *.nlx.io

```
bart@192  ~  dig adfasdsdaf.nlx.io

; <<>> DiG 9.9.7-P3 <<>> adfasdsdaf.nlx.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64951
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;adfasdsdaf.nlx.io.		IN	A
```

**Comment by ehotting** [comment]
Will request again, and let's arrange own nameservers:  #13

**Comment by bartjkdp** [comment]
Updated the records above to be more precise

**Comment by ehotting** [comment]
@bartjkdp Appears the records are updated, can you review & close?

**Comment by bartjkdp** [comment]
All fine now!
