### ISSUE TITLE
Arrange own nameservers for more flexibility

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#13]
Depending on external sysadmins for every DNS change is not pleasant for both NLX team and sysadmins. We need our own nameservers.

**Comment by bartjkdp** [comment]
DNS hosting account requested through CloudVPS support

**Comment by ehotting** [comment]
Account for DNS hosting received, records configured. Requested to point to the new nameservers at registrar.

**Comment by ehotting** [comment]
Received confirmation, records at registar now point to our own nameservers. @bartjkdp, can you review, and close when confirmed.

`httng@x: ~/code/github.com/VNG-Realisatie/nlx $ dig nlx.io +nssearch
SOA ns1.cloudvps.com. hostmaster.cloudvps.com. 2018011812 14400 3600 604800 86400 from server 79.170.92.6 in 7 ms.
SOA ns1.cloudvps.com. hostmaster.cloudvps.com. 2018011812 14400 3600 604800 86400 from server 194.60.207.55 in 7 ms.
SOA ns1.cloudvps.com. hostmaster.cloudvps.com. 2018011812 14400 3600 604800 86400 from server 194.60.207.54 in 7 ms.
httng@x: ~/code/github.com/VNG-Realisatie/nlx $`

**Comment by bartjkdp** [comment]
Looks good to me. This issue is closed.
