### ISSUE TITLE
Link to documentation is malformed

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/nlx#131]
The link to documentation of the eSuiteGateway has this form:
https://directory.demo.nlx.io/87.249.99.222/ESuiteGatewayV1?wsdl

So directory url plus the original documentation URL.

Hugo

**Comment by bartjkdp** [comment]
Hey Hugo,

Thanks for your question. This is a problem Dimpact can solve, they misconfigured their documentation URL. Their `service-config.toml` file probably looks like:

    documentation-url = "87.249.99.222/ESuiteGatewayV1?wsdl"

This should be:

    documentation-url = "https://87.249.99.222/ESuiteGatewayV1?wsdl"
