### ISSUE TITLE
Contact Kadaster to get more info on rewrite requirements

### ISSUE THREAD

**Issue by bartjkdp** [VNG-Realisatie/nlx#145]

**Comment by ehotting** [comment]
Contact @fterpstra for this user task

**Comment by fterpstra** [comment]
If you cannot get a test account for Beeldmateriaal in the short term, you can test with any public WMS service from PDOK https://www.pdok.nl/nl/producten/pdok-services/overzicht-urls and put your own NLX node in front of it to simulate what beeldmateriaal does.
