### ISSUE TITLE
Setup hugo structure for docs

### ISSUE THREAD

**Issue by GeertJohan** [VNG-Realisatie/nlx#18]
The docs folder should contain a [hugo](https://gohugo.io/) structure so we have a way to organize docs and can easily deploy the docs as a static site.

**Comment by bvhme** [comment]
I also always enjoy using GitHub pages and its Jekyll static site generator since it is relatively powerful needs little config and GitHub will automatically build it for you. It can even be set to build from the `docs/` directory. It does not support extracting documentation from code etc, so that might also be a good reason to go for a different system.

**Comment by GeertJohan** [comment]
Hugo is very popular within the Go community and therefore known well with our target audience of developers. I generally treat the docs as yet another micro-service/component of a project. Its built into a container image and released with the same versioning structure as other components. This does assume that the docs are self-hosted, instead of github-hosted. Its a bit more work, but you gain that docs container images at a certain version reflect the other components at that version. Since we already have a kubernetes cluster, hosting the docs container will become quite trivial and just a piece of the usual deployment.

**Comment by bvhme** [comment]
Good. I like treating the docs the same way as code. Requiring spinning up
a container to serve static files is something I need to get used to, but I
guess people can also just do `hugo server -D` in their command line.

I'd love to take this issue on a chance to learn a bit about `hugo`.



Boris van Hoytema

—

   - E-mail boris@vanhoytema.com
   - Website bvh.me
   - Twitter twitter.com/bvhme
   - Facebook facebook.com/vanhoytema <http://www.facebook.com/vanhoytema>
   - LinkedIn linkedin.com/in/borisvanhoytema
   <http://nl.linkedin.com/in/borisvanhoytema>

**Comment by bvhme** [comment]
Not that it matters too much, but so is Jekyll, it is just an Open Source Ruby lib. It is Ruby however and that is a good reason to not include it in this project.

**Comment by bartjkdp** [comment]
Oh yeah you are right, did not read it correctly. Sure.

**Comment by bvhme** [comment]
I've done some exploring of this and think that at this moment having a site generated with Hugo is overkill for now and adds a large amount of complexity to this codebase that we don't need yet.

I would propose seeing the GitHub repo as our main target for documentation. We can switch to Hugo once we find ourselves in a situation where the complexity of the documentation begs for a more complex site.

Can we move this issue to the icebox for now?

**Comment by GeertJohan** [comment]
I'd be happy to set up Hugo once we have containerized our components (in a few sprints).

> Can we move this issue to the icebox for now?

Sure, backlog bottom?

**Comment by ehotting** [comment]
Is it possible to make the structure ready for multi-language support? Dutch content will follow later.

**Comment by GeertJohan** [comment]
That makes total sense for the nlx.io frontend. But is it really needed for architect/developer/sysadmin documentation?
In any case, it's quite simple to later add multi-lang support with hugo: https://gohugo.io/content-management/multilingual/

**Comment by ehotting** [comment]
It's government, most of the architectural docs will have to be in Dutch. Can be done later indeed, just wanted to make sure it can be added later

**Comment by GeertJohan** [comment]
https://github.com/VNG-Realisatie/nlx/pull/47
