### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#19]
Advised: EUPL

**Comment by bartjkdp** [comment]
+1 for EUPL. We could use [Developer Certificate of Origin](https://developercertificate.org/) for contributors.

**Comment by bvhme** [comment]
+1

EUPL is a good choice, also because the EUPL team is fairly responsive to questions you might have about it in addition to it being easy to use in court in the Netherlands.

I suggest moving forward with this and re-licencing if that seems necessary later. Now that this project is in its infancy that is hopefully not a problem.

**Comment by bvhme** [comment]
I'm going to start off with asking the EUPL people which language to include both for legal and developer reasons. English code, Dutch law.

**Comment by bvhme** [comment]
Gotten a reply

> One of the unique features of the EUPL, compared to other free licenses, is that it has a legal working value in all (23) languages, as published in the Official Journal (19.5.2017 – L128/60 - for the last version 1.2).
>
> English recipients will read:
> 13.  … All linguistic versions of this Licence, approved by the European Commission, have identical value. Parties can take advantage of the linguistic version of their choice.
> 15.   Applicable Law
> Without prejudice to specific agreement between parties,
— this Licence shall be governed by the law of the European Union Member State where the Licensor has his seat, resides or has his registered office,
>
> While Dutch recipients/speakers will read:
> 13.  … Alle door de Europese Commissie goedgekeurde taalversies van deze licentie hebben dezelfde waarde. De partijen kunnen zich beroepen op de taalversie van hun keuze.
> 15.Toepasselijk recht Onverminderd specifieke overeenkomsten tussen de partijen, —  wordt deze licentie beheerst door het recht van de lidstaat van de Europese Unie waar de licentiegever zijn statutaire zetel, verblijfplaats of hoofdkantoor heeft,
>
> Therefore, the fact your code is internationalised with comments in English only has no impact on applicable law, neither on the right of recipients to use and refer to the EUPL licence written in their native language. This does not change even if the licensor provides only the English version in the “LICENCE FILE” included in a download package. The licensor could as well provide several linguistic versions of the EUPL in the “LICENCE FILE”, for example EN and NL, but this is not at all mandatory.
>
> The mention in the source code “Licensed under the EUPL” is the minimal requirement that automatically refers to the last version in all published languages.

Apparently I was reading the licence with my nose, and would say it is wise to proceed!

**Comment by bvhme** [comment]
As an interesting side note, [Barcelona is licencing Sentilo both EUPL and LGPL](https://github.com/sentilo/sentilo/blob/master/LICENSE)

**Comment by bartjkdp** [comment]
Nice research 👍
