### ISSUE TITLE
Add readme documentation about git branching model.

### ISSUE THREAD

**Issue by GeertJohan** [VNG-Realisatie/nlx#2]

**Comment by bvhme** [comment]
This could be a great start for a `CONTRIBUTING.md`. :)

Is this repo using Git-Flow?

**Comment by bartjkdp** [comment]
We are thinking of a lighter model of GitFlow: OneFlow. [This](http://endoflineblog.com/gitflow-considered-harmful) and [this](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) article give a more in-depth discussion about the pros and cons of this model.

**Comment by bvhme** [comment]
Great, sounds like a good choice! As long as we're able to save our commit history with the messages I think we'll be fine either way.
