### ISSUE TITLE
Add Developer Certificate of Origin

### ISSUE THREAD

**Issue by bvhme** [VNG-Realisatie/nlx#20]
@bartjkdp mentioned the following DCO: https://github.com/Quixote-project/backend2/blob/master/CONTRIBUTING

**Comment by bartjkdp** [comment]
@ehotting do we need some legal review from VNG on this? Pretty curious if their legal department agrees on DCO. I think it is a good choice mainly due to [these](https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/) arguments, but not sure if they would like to have more control?

**Comment by ehotting** [comment]
@arnoudquanjer can you research this or ask someone to do so?

**Comment by bvhme** [comment]
Personally, I feel the Chain of Authorship (EUPL art 6) can provide in most of what we need here and I am not interested in gaining more control over the copyright than what is necessary to develop this Open Source codebase. I would personally prefer for now continuing without a DCO until this actually becomes an issue.

**Comment by bvhme** [comment]
The general consensus now is in the team that – although we are still uncertain if we need a DCO or CLA in order to be safe from lawsuits and are waiting for the VNG lawyers to explain this to us – we're going to move ahead without one for now.

Our fear is that organisations could – even after a contribution in the EUPL licenced codebase – rescind the licence on the basis of a person in the organisation not having been authorised to provide the licence. @bartjkdp remembered something about Dutch law that might make this possible.

@arnoudquanjer is going to check with the lawyers of VNG and report back to us here.
