### ISSUE TITLE
Get the marketing page online

### ISSUE THREAD

**Issue by bartjkdp** [VNG-Realisatie/nlx#215]

**Comment by ehotting** [comment]
Can be moved to main domain in current state, rather than sub domain _marketing_

**Comment by bartjkdp** [comment]
Will do this today

**Comment by ehotting** [comment]
Done

**Comment by ehotting** [comment]
nlx.io redirects to docs.nlx.io

**Comment by bartjkdp** [comment]
Probably cached by your browser?

**Comment by ehotting** [comment]
Yep.
