### ISSUE TITLE
Add basic alerting on availability of services

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#23]

**Comment by bartjkdp** [comment]
We could probably use best something like Datadog or Sentry for this. What do you think?

**Comment by ehotting** [comment]
Nice for sprint > 4, for now I'll add something KISS, if you're OK with that

**Comment by bartjkdp** [comment]
Fine 👍

**Comment by ehotting** [comment]
We now have UptimeRobot alerting to Slack
