### ISSUE TITLE
As a developer I want to have a CA and CA-signed certificates to develop/test inway/outway communication.

### ISSUE THREAD

**Issue by GeertJohan** [VNG-Realisatie/nlx#33]
We could use https://github.com/cloudflare/cfssl to setup our own CA.

Since this CA and signed certs are meant to be used to develop and test, all private keys can be publicly readable in the repository.

**Comment by bartjkdp** [comment]
A small example how to setup a CA and some certificates can be found [over here](https://github.com/Pleio/tenantcontroller).
