### ISSUE TITLE
Enable DNSSEC for nlx.io

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#39]
Since transfer to nameservers of CloudVPS we lost DNSSEC. This is not optional, so we need to fix it.

**Comment by bartjkdp** [comment]
I asked CloudVPS, but I am not sure they offer DNSSEC for .io domains...

**Comment by ehotting** [comment]
I'm afraid there is no support for DNSSEC on their nameservers at all. Should not be dependent on TLD anyway, if the root supports it - which is the case for .io .
Which means we need to move nameservers again. Let's postpone that for now.

**Comment by ehotting** [comment]
We don't have a legal entity that can do this right now. Perhaps your foundation?

**Comment by bartjkdp** [comment]
We have no problems holding the domain for a while. Just let me know, so we can initiate the transfer.

**Comment by bartjkdp** [comment]
Duplicate of #40
