### ISSUE TITLE
As product owner I want the infra security hygiene to be spotless

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#40]
- [x] DNSSEC #39
- [x] 100% @ https://internet.nl/site/nlx.io/     (and all subdomains)
- [x] 100% @ https://internet.nl/mail/nlx.io/   
- [x] A+  @ https://www.ssllabs.com/ssltest/analyze.html?d=nlx.io&hideResults=on&latest
- [x] A @ https://securityheaders.io/?q=nlx.io&hide=on&followRedirects=on

**Comment by bartjkdp** [comment]
Almost all finished

**Comment by ehotting** [comment]
🎉

**Comment by bartjkdp** [comment]
Yeah we are there!
