### ISSUE TITLE
As product owner I want a permanent demo API via NLX node online

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#42]
- [x] Following [DSO API and URI strategy](https://aandeslagmetdeomgevingswet.nl/digitaal-stelsel/nieuws-dso/nieuws/api-uri-strategie/)
- [x] Demo API in repo [nlx-demo](https://github.com/VNG-Realisatie/nlx-demo)
- [x] Demo NLX node always runs latest build

**Comment by bartjkdp** [comment]
Did some initial work on the [feature/demo-api](https://github.com/VNG-Realisatie/nlx-demo/tree/feature/demo-api) branch. Maybe this demo API should just return an echo containing the organisation name of the requester (if available) and the local time?

Would be cool to have another demo API that does something more interesting.

**Comment by jwijnings** [comment]
I always use Celsius-Fahrenheit as a demo, people get the conversion
immediately. :-)

Op wo 21 feb. 2018 19:44 schreef Bart J <notifications@github.com>:
