### ISSUE TITLE
Administrate credentials infra

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#43]

**Comment by GeertJohan** [comment]
https://www.passwordstore.org/

**Comment by bartjkdp** [comment]
Added all credentials to git@git.bartj.com:nlx/credentials.git. Repository can be moved but should be private imo.

**Comment by bartjkdp** [comment]
Think this issue is resolved, see the Pass-encrypted repository on [https://git.bartj.com/nlx/credentials](https://git.bartj.com/nlx/credentials) for more details.
