### ISSUE TITLE
Write functional design detailing all logging requirements

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#5]
The logging requirements in de [product vision](https://github.com/VNG-Realisatie/nlx/blob/master/docs/product-vision.md#protocol-api-requests) will have impact on the fundamental design. Detailed functional design is required.

**Comment by adgerrits** [comment]
The fundamental question that has to be answered first is if en to wich level NLX has to log data. The primary responsibility for logging is with business-app A and business-app B that exchange data with NLX functioning as an intermediate. I think it's a good starting point to minimize logging data and look out for the pitfall to log more than absolutely required request related data (f.i. all authentication and authorization related data). A second point of interest is the need of organizations to be able to merge distributed saved logging data so flexible log-data retrieval has to be possible.

**Comment by ehotting** [comment]
By moving the (formal) logging of the use of API's to NLX, as described in the product vision [here](https://github.com/VNG-Realisatie/nlx/blob/master/docs/product-vision.md#protocol-api-requests), it becomes within reach to standardise formal logging for several purposes. Also, the responsibility can be removed from each individual application - instead the application has to make sure each request to an API includes all required metadata. The formal logs are on the business layer, and are independent of the technical logs of webservers, firewalls and so on. In the functional design we should discuss what should and should not be part of the logging that NLX takes care of. The design should allow for later expansion of those requirements.
