### ISSUE TITLE
How can I configure the NLX

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/nlx#75]
I managed to get the software running on an Ubuntu machine. But how can I configure the NLX, that is register an API and send requests that are then routed to the right service/endpoint?

Hugo

**Comment by ehotting** [comment]
For that we need the 'directory' which is the NLX service registry. Issues #59 and #60 are planned for [sprint 3](https://github.com/VNG-Realisatie/nlx/projects/1?) which ends soon. Right now you could call the API through NLX like this: https://docs.nlx.io/development/components/outway/

**Comment by ehotting** [comment]
Directory is up 'n running   ([demo](https://directory.demo.nlx.io)
